services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  celery_worker:
    build: .
    command: celery -A server.queue.task_queue.celery_app worker --loglevel=info --concurrency=2
    depends_on:
      - redis
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
